// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcr_C4wmLxdgvru7G-MNsDfLJEhjA3FiI',
    appId: '1:569575038698:web:24b8a3aea254fbef3b0193',
    messagingSenderId: '569575038698',
    projectId: 'voice-voyage-5212c',
    authDomain: 'voice-voyage-5212c.firebaseapp.com',
    storageBucket: 'voice-voyage-5212c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzwk-h2l-AiPILvAk17iX2BFVs2YS11us',
    appId: '1:569575038698:android:84ff73dc4974548a3b0193',
    messagingSenderId: '569575038698',
    projectId: 'voice-voyage-5212c',
    storageBucket: 'voice-voyage-5212c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSlNazaAkcRrupMrAc-Y3agIUXoRl3YqY',
    appId: '1:569575038698:ios:405aef7fb32015c13b0193',
    messagingSenderId: '569575038698',
    projectId: 'voice-voyage-5212c',
    storageBucket: 'voice-voyage-5212c.firebasestorage.app',
    iosBundleId: 'com.example.voiceVoyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSlNazaAkcRrupMrAc-Y3agIUXoRl3YqY',
    appId: '1:569575038698:ios:405aef7fb32015c13b0193',
    messagingSenderId: '569575038698',
    projectId: 'voice-voyage-5212c',
    storageBucket: 'voice-voyage-5212c.firebasestorage.app',
    iosBundleId: 'com.example.voiceVoyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcr_C4wmLxdgvru7G-MNsDfLJEhjA3FiI',
    appId: '1:569575038698:web:bb16aaf5e22da1cc3b0193',
    messagingSenderId: '569575038698',
    projectId: 'voice-voyage-5212c',
    authDomain: 'voice-voyage-5212c.firebaseapp.com',
    storageBucket: 'voice-voyage-5212c.firebasestorage.app',
  );
}
